### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by leha-code** [MCPI-Revival/mcpiedit#4]
What is the license of this project. Please add a license.

**Comment by TheBrokenRail** [comment]
MIT.

**Comment by leha-code** [comment]
Thanks. Nobody said that in DM, but according to choosealicense.com, 
> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

So I was unsure if I can use this, without the license being officially here.

**Comment by nobody5050** [comment]
MIT.

**Comment by TheBrokenRail** [comment]
Well, there's a file in the repo now.
